# Generated by Django 5.2.6 on 2026-08-31 21:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(help_text='Signed: positive enters stock, negative leaves it.')),
                ('movement_type', models.CharField(choices=[('INITIAL_STOCK', 'Initial stock'), ('PURCHASE', 'Purchase receipt'), ('SALE', 'Sale'), ('RETURN', 'Customer return'), ('ADJUSTMENT', 'Manual adjustment'), ('TRANSFER', 'Transfer between locations')], db_index=True, max_length=20)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('source_type', models.CharField(blank=True, db_index=True, max_length=30)),
                ('source_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True, help_text='When it happened in the store, which may predate sync.')),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'inventory_movements',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'location', 'variant', '-occurred_at'], name='inventory_m_organiz_ad02de_idx'), models.Index(fields=['organization', 'source_type', 'source_id'], name='inventory_m_organiz_bd8ee3_idx'), models.Index(fields=['organization', '-created_at'], name='inventory_m_organiz_b03b3b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='ck_inventory_movement_quantity_nonzero')],
            },
        ),
        migrations.CreateModel(
            name='StockDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_before', models.IntegerField()),
                ('quantity_requested', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('source_type', models.CharField(blank=True, max_length=30)),
                ('source_id', models.CharField(blank=True, max_length=64)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_discrepancies', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_discrepancies', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_discrepancies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_resolved', '-created_at'], name='stock_discr_organiz_d95a45_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_point', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'stock_levels',
                'indexes': [models.Index(fields=['organization', 'location'], name='stock_level_organiz_7b087f_idx'), models.Index(fields=['organization', 'variant'], name='stock_level_organiz_8110be_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'variant'), name='uq_stock_level_location_variant')],
            },
        ),
    ]
