line-length = 110
target-version = "py312"

[lint]
select = ["E", "F", "I", "UP", "B", "DJ"]
ignore = ["B008"]

[lint.per-file-ignores]
"*/migrations/*" = ["E501"]
"config/settings/*" = ["F403", "F405"]
"scripts/*" = ["E501"]
