"""Abstract bases plus the two cross-cutting tables: AuditLog and IdempotencyKey."""
from __future__ import annotations

import uuid

from django.conf import settings
from django.db import models

from .managers import TenantManager


class UUIDModel(models.Model):
    """UUID primary keys.

    Required by the offline-first design: a POS terminal without connectivity
    must be able to mint the final identifier of a sale locally, so that
    syncing never rewrites ids the cashier already printed on a receipt.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class TenantScopedModel(UUIDModel, TimeStampedModel):
    """Every row that belongs to a business inherits from this.

    `objects` is tenant-filtered and is the default manager, so reverse
    relations are filtered too. `all_objects` is unfiltered and exists for
    platform-level maintenance, migrations and the admin.
    """

    organization = models.ForeignKey(
        "organizations.Organization",
        on_delete=models.CASCADE,
        related_name="%(app_label)s_%(class)s_set",
    )

    # Declared in this order on purpose: the first manager becomes
    # `_default_manager`, which is what reverse relations use. Isolation must
    # be the default even when data is reached through a relation.
    objects = TenantManager()
    all_objects = models.Manager()  # noqa: DJ012 - see comment above

    class Meta:
        abstract = True


class AuditLog(TenantScopedModel):
    """Append-only record of who did what, when.

    Written explicitly from service functions rather than from signals: a
    signal knows a row changed, but not the business intent behind it.
    """

    action = models.CharField(max_length=64, db_index=True)
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="audit_logs",
    )
    actor_label = models.CharField(max_length=254, blank=True)
    object_type = models.CharField(max_length=64, blank=True, db_index=True)
    object_id = models.CharField(max_length=64, blank=True, db_index=True)
    metadata = models.JSONField(default=dict, blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)

    class Meta:
        db_table = "audit_log"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["organization", "-created_at"]),
            models.Index(fields=["organization", "action", "-created_at"]),
            models.Index(fields=["organization", "object_type", "object_id"]),
        ]

    def __str__(self) -> str:
        return f"{self.action} by {self.actor_label or 'system'} at {self.created_at:%Y-%m-%d %H:%M}"


class IdempotencyKey(TenantScopedModel):
    """Deduplicates critical writes.

    Serves both HTTP retries (`Idempotency-Key` header) and offline sync
    (`operation_id` generated by the device): they are the same problem, so
    they share one mechanism instead of two.
    """

    class Status(models.TextChoices):
        IN_PROGRESS = "IN_PROGRESS", "In progress"
        COMPLETED = "COMPLETED", "Completed"

    key = models.CharField(max_length=128)
    endpoint = models.CharField(max_length=128)
    request_hash = models.CharField(max_length=64)
    status = models.CharField(max_length=16, choices=Status.choices, default=Status.IN_PROGRESS)
    response_status = models.PositiveSmallIntegerField(null=True, blank=True)
    response_body = models.JSONField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "idempotency_key"
        constraints = [
            models.UniqueConstraint(fields=["organization", "key"], name="uq_idempotency_org_key"),
        ]
        indexes = [models.Index(fields=["organization", "-created_at"])]

    def __str__(self) -> str:
        return f"{self.key} ({self.status})"


class DocumentSequence(TenantScopedModel):
    """Per-tenant consecutive numbering for sales, purchases and refunds.

    A store's documents must be numbered without gaps, which means the counter
    is a serialisation point: the row is locked until the transaction that took
    a number commits. That is deliberate. Two registers in the same store
    therefore complete sales one after the other, for a few milliseconds each -
    the cost of never issuing the same receipt number twice, which matters more
    once electronic invoicing arrives.

    The lock is per (organization, location, document_type), so two stores, or
    a sale and a purchase, never wait on each other.
    """

    class DocumentType(models.TextChoices):
        SALE = "SALE", "Sale"
        PURCHASE = "PURCHASE", "Purchase"
        REFUND = "REFUND", "Refund"

    location = models.ForeignKey(
        "organizations.Location", on_delete=models.CASCADE, related_name="document_sequences"
    )
    document_type = models.CharField(max_length=20, choices=DocumentType.choices)
    prefix = models.CharField(max_length=8, blank=True)
    last_number = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = "document_sequences"
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "location", "document_type"],
                name="uq_document_sequence",
            ),
        ]

    def __str__(self) -> str:
        return f"{self.document_type}@{self.location_id}={self.last_number}"
