# Generated by Django 5.2.6 on 2026-09-06 02:42

from django.db import migrations, models

import apps.catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=apps.catalog.models.product_photo_path),
        ),
    ]
