# Generated by Django 5.2.6 on 2026-08-31 21:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('document_type', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('NIT', 'NIT'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], default='', max_length=10)),
                ('document_number', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='customers_organiz_f33128_idx'), models.Index(fields=['organization', 'phone'], name='customers_organiz_15a402_idx'), models.Index(fields=['organization', 'document_number'], name='customers_organiz_88722c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('document_number', ''), _negated=True), fields=('organization', 'document_number'), name='uq_customer_org_document')],
            },
        ),
    ]
