# Generated by Django 5.2.6 on 2026-08-31 21:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(help_text='Stable id generated by the terminal.', max_length=64)),
                ('name', models.CharField(max_length=80)),
                ('platform', models.CharField(blank=True, max_length=40)),
                ('app_version', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=128)),
                ('token_issued_at', models.DateTimeField(blank=True, null=True)),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='cash.cashregister')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_id', models.UUIDField()),
                ('operation_type', models.CharField(choices=[('SALE_CREATE', 'Create sale'), ('SALE_CANCEL', 'Cancel sale'), ('REFUND_CREATE', 'Create refund')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('PROCESSED', 'Processed'), ('FAILED', 'Failed')], db_index=True, max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('error_detail', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='synchronization.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_operations',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('organization', 'identifier'), name='uq_device_org_identifier'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['organization', 'status', '-received_at'], name='sync_operat_organiz_6a9011_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['organization', 'device', '-received_at'], name='sync_operat_organiz_035b26_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('organization', 'operation_id'), name='uq_sync_operation_org_id'),
        ),
    ]
