"""Offline-first synchronisation.

The POS keeps selling when the connection drops. Every operation it performs
offline is stamped with a UUID the terminal generates, and replayed later.
The server must accept the same operation any number of times and apply it
exactly once - a till with a flaky connection will retry.

SyncOperation is both the deduplication key and the operational record: what
arrived, from which device, what happened to it, and why it failed if it did.
"""
from __future__ import annotations

from django.conf import settings
from django.db import models

from apps.core.models import TenantScopedModel


class Device(TenantScopedModel):
    """A terminal allowed to push offline operations.

    Registering a device is an online, authenticated act. It gives every
    synced operation a traceable origin, and gives the store a way to cut off
    a lost or stolen till without touching anyone's password.
    """

    location = models.ForeignKey(
        "organizations.Location", on_delete=models.PROTECT, related_name="devices"
    )
    identifier = models.CharField(max_length=64, help_text="Stable id generated by the terminal.")
    name = models.CharField(max_length=80)
    platform = models.CharField(max_length=40, blank=True)
    app_version = models.CharField(max_length=20, blank=True)
    cash_register = models.ForeignKey(
        "cash.CashRegister",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="devices",
    )
    is_active = models.BooleanField(default=True)
    last_seen_at = models.DateTimeField(null=True, blank=True)
    last_sync_at = models.DateTimeField(null=True, blank=True)
    # Hashed like a password. Presented at login as X-Device-Token so the till
    # resolves its own business and the cashier only types a username and
    # password. Handed out in the clear exactly once, when the terminal
    # registers.
    token = models.CharField(max_length=128, blank=True)
    token_issued_at = models.DateTimeField(null=True, blank=True)
    registered_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="devices"
    )

    class Meta:
        db_table = "devices"
        ordering = ["name"]
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "identifier"], name="uq_device_org_identifier"
            ),
        ]

    def __str__(self) -> str:
        return f"{self.name} ({self.identifier})"


class SyncOperation(TenantScopedModel):
    """One operation captured offline and replayed to the server."""

    class Type(models.TextChoices):
        SALE_CREATE = "SALE_CREATE", "Create sale"
        SALE_CANCEL = "SALE_CANCEL", "Cancel sale"
        REFUND_CREATE = "REFUND_CREATE", "Create refund"

    class Status(models.TextChoices):
        PROCESSED = "PROCESSED", "Processed"
        FAILED = "FAILED", "Failed"

    # Generated by the terminal. Unique per tenant: this is what makes the
    # whole protocol idempotent.
    operation_id = models.UUIDField()
    device = models.ForeignKey(Device, on_delete=models.PROTECT, related_name="operations")
    operation_type = models.CharField(max_length=30, choices=Type.choices, db_index=True)
    status = models.CharField(max_length=20, choices=Status.choices, db_index=True)

    payload = models.JSONField(default=dict)
    result = models.JSONField(null=True, blank=True)
    error_code = models.CharField(max_length=40, blank=True)
    error_detail = models.TextField(blank=True)

    # When the terminal performed it, versus when the server heard about it.
    occurred_at = models.DateTimeField(null=True, blank=True)
    received_at = models.DateTimeField(auto_now_add=True, db_index=True)
    processed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="sync_operations",
    )

    class Meta:
        db_table = "sync_operations"
        ordering = ["-received_at"]
        constraints = [
            models.UniqueConstraint(
                fields=["organization", "operation_id"], name="uq_sync_operation_org_id"
            ),
        ]
        indexes = [
            models.Index(fields=["organization", "status", "-received_at"]),
            models.Index(fields=["organization", "device", "-received_at"]),
        ]

    def __str__(self) -> str:
        return f"{self.operation_type} {self.operation_id} ({self.status})"


# Module-level alias so drf-spectacular can name this enum in the OpenAPI
# schema; its override loader cannot traverse into a nested class.
SYNC_OPERATION_STATUS_CHOICES = SyncOperation.Status.choices
