# Generated by Django 5.2.6 on 2026-08-31 21:48

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cash', '0001_initial'),
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially refunded')], default='DRAFT', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refunded_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source', models.CharField(choices=[('POS', 'Point of sale'), ('SYNC', 'Synced from an offline terminal')], default='POS', max_length=10)),
                ('device_id', models.CharField(blank=True, help_text='Terminal that created it offline.', max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=240)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='cash.cashsession')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, default='', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], default='CASH', max_length=20)),
                ('restock', models.BooleanField(default=True, help_text='False when the goods come back damaged and cannot be resold.')),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='cash.cashsession')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sales.sale')),
            ],
            options={
                'db_table': 'refunds',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('OTHER', 'Otro')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('reference', models.CharField(blank=True, help_text='Voucher, approval code.', max_length=80)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=220)),
                ('sku', models.CharField(max_length=64)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taxable_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('refunded_quantity', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.productvariant')),
            ],
            options={
                'db_table': 'sale_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.refund')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_items', to='sales.saleitem')),
            ],
            options={
                'db_table': 'refund_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status', '-occurred_at'], name='sales_organiz_b1ba2c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'location', '-occurred_at'], name='sales_organiz_4e3358_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'customer', '-occurred_at'], name='sales_organiz_a7b8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'cash_session'], name='sales_organiz_1d4e36_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uq_sale_org_number'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['organization', '-occurred_at'], name='refunds_organiz_8e6af0_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('organization', 'number'), name='uq_refund_org_number'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'method'], name='payments_organiz_edb1d1_idx'),
        ),
        migrations.AddIndex(
            model_name='saleitem',
            index=models.Index(fields=['organization', 'variant'], name='sale_items_organiz_005e23_idx'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_quantity__lte', models.F('quantity'))), name='ck_sale_item_refund_within_sold'),
        ),
    ]
