# Generated by Django 5.2.6 on 2026-08-31 21:48

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('tax_id', models.CharField(blank=True, help_text='NIT / RUT.', max_length=40)),
                ('country', models.CharField(default='CO', max_length=2)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('currency_decimals', models.PositiveSmallIntegerField(default=0, help_text='Smallest circulating unit. COP has no cents.')),
                ('timezone', models.CharField(default='America/Bogota', max_length=64)),
                ('prices_include_tax', models.BooleanField(default=True)),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=19, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization')),
            ],
            options={
                'db_table': 'locations',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='uq_location_org_code'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='uq_location_one_default_per_org')],
            },
        ),
    ]
